### ISSUE TITLE
EPIC: Create basic timer UI and functionality (MVP)

### ISSUE THREAD

**Issue by nmpereira** [CommunityFocus/CommunityFocus#1]
## What
Add some basic functionality to the timer as follows

### Stage 1
- [ ] CommunityFocus/CommunityFocus#17
- [ ] CommunityFocus/CommunityFocus#16
- [ ] CommunityFocus/CommunityFocus#15
- [ ] CommunityFocus/CommunityFocus#14
- [x] CommunityFocus/CommunityFocus#13
- [x] CommunityFocus/CommunityFocus#21
- [ ] CommunityFocus/CommunityFocus#9
- [ ] CommunityFocus/CommunityFocus#11
- [x] CommunityFocus/CommunityFocus#8
- [ ] #54
- [x] Add a refresh button on the LandingPage so the user can cycle between multiple server suggested timer names
- [x] #53
- [x] CommunityFocus/CommunityFocus#18
- [ ] Add color scheme
- [ ] Update the main readme
- [ ] Add a get started guide
- [ ] CommunityFocus/CommunityFocus#7
- [ ] CommunityFocus/CommunityFocus#10

### Stage 2
- [ ] CommunityFocus/CommunityFocus#6
- [ ] Add cypress testing framework
- [x] CommunityFocus/CommunityFocus#22
- [x] #55
- [ ] #31
- [x] #30
- [x] CommunityFocus/CommunityFocus#19

### Stage 3
- [x] Add change history to the current timer
- [x] #99
- [x] Host the app
- [x] #32
- [x] Add name bubbles to show who's currently in the timer
- [ ] Add custom ring options at the end of the countdown (volume, ring type, continuous/short ring etc)

### Pre-release
- [ ] Bug hunt
- [x] #33
